### ISSUE TITLE
Document a policy for required CI health before we can release

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/website#1001]
We should document the required CI health (i.e expected green periodics against release-next branch) before we can release (and stick to that policy)

We had some discussion about this on Slack https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1654700467188109?thread_ts=1654691889.270499&cid=CDEQJ0Q8M

**Comment by wallrj** [comment]
There's now a line in the release process about this:

> The relevant [testgrid dashboard](https://testgrid.k8s.io/cert-manager) should not be failing for the release you're trying to perform.

-- https://cert-manager.io/docs/contributing/release-process/#prerequisites
