### ISSUE TITLE
Use descriptive text instead of alt for `feature icon`

### ISSUE THREAD

**Issue by jsoref** [cert-manager/website#1006]
The key features section of https://cert-manager.io/ looks like this:
![image](https://user-images.githubusercontent.com/2119212/173421707-92c280f6-3771-4093-a122-426f45c7fab4.png)
unless you turn on images:
![image](https://user-images.githubusercontent.com/2119212/173421727-9f323cd4-e4a9-4c9a-afc3-f3cc0d92a99e.png)

**Comment by inteon** [comment]
fixed in #1232
