### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by smlehman** [cert-manager/website#103]
It appears that there needs to be a slight modification in the helm install command on https://cert-manager.io/docs/installation/kubernetes/ 

Currently it reads:
$ helm install \
  --name cert-manager \
  --namespace cert-manager \
  --version v0.13.0 \
  jetstack/cert-manager

Turns out that Helm doesn't want the `--name` flag as this returns
`Error: unknown flag: --name`

This does work: 
$ helm install \
  cert-manager \
  --namespace cert-manager \
  --version v0.13.0 \
  jetstack/cert-manager

**Comment by meyskens** [comment]
Closing as a duplicate of #92
