### ISSUE TITLE
Why TLS type secret have an extra data `ca.crt`? 

### ISSUE THREAD

**Issue by earik87** [cert-manager/website#1116]
**Issue:**
When I follow instructions in the ["Verifying the Installation" section](https://cert-manager.io/docs/installation/verify/), it creates a secret called `selfsigned-cert-tls`. But weirdo is it has three data: ca.crt, tls.crt, tls.key. And it is a tls type secret. 

According to the [documentation](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) of kubernetes, tls type secrets only have two data: tls.crt and tls.key. But, here we have ca.crt inside the secret. It seems that ca.crt and tls.crt are the same. kubectl command allows this. However, why do we have a duplicate of one certificate data then?

<img width="789" alt="image" src="https://user-images.githubusercontent.com/36437947/203074286-81e33e15-ed2d-4784-86e5-032379816f49.png">

**Comment by wallrj** [comment]
You can read the background here: https://github.com/cert-manager/cert-manager/pull/848
 * https://github.com/cert-manager/cert-manager/pull/848

And it's mentioned in the documentation here:
 * https://cert-manager.io/docs/concepts/certificate/

I hope that answers your question.
