### ISSUE TITLE
New version of adcs-issuer

### ISSUE THREAD

**Issue by djkormo** [cert-manager/website#1132]
I've decided to renew the code for adcs-issuer. Now it works with cert-manager 1.9.x and fully supports ntlm.

This work is still in progress. Helm chart will be in few next releases.

My repo link: 
https://github.com/djkormo/adcs-issuer

Linked to:

https://github.com/cert-manager/website/pull/1077

**Comment by djkormo** [comment]
I forked the most "deep" version and I have made changes to use this plugin
with 1.9.1 cert manager. The original version for using the old cert
manager API (beta). I haven't so far to talk to other people. The Nokia
code is outdated and imposibble to use at this moment.

With best regards,

Krzysztof Pudłowski


czw., 12 sty 2023 o 13:16 Richard Wall ***@***.***>
napisał(a):

**Comment by wallrj** [comment]
@mmlt @SimeonPoot @jimbali @gellner @pearj @dimatha You all have forks of the adcs issuer which are ancestors of @djkormo 's fork . Please weigh in on which version you now consider to be the official / best version. 

@CsatariGergely and @chojnack You both contributed to the original Nokia project (AFAICS) so please comment if you have time.  Which of the forks you consider to be the official version.

xref
 * https://github.com/nokia/adcs-issuer/issues/14

**Comment by CsatariGergely** [comment]
Unfortunately we are not maintaining the original project anymore, but honestly I can not and do not want to define the official successor of the original Nokia code. I'm happy to add a note to the README to the original repo to clarify the situation if needed.

**Comment by SimeonPoot** [comment]
Hi there, at the moment I'm not maintaining any of the adcs-issuer code anymore. Made a few adjustments to make it working for the company I was with at that time, (I think the same goes for mmlt, as we teamed up). 

If I need to do something for you guys, lemme know. 

Good luck!

**Comment by jimbali** [comment]
Unfortunately I was never able to complete the work that I needed this for, as I was blocked by another couple of departments for almost a year, and then the company went bust. I no longer have access to an ADCS server.

**Comment by pearj** [comment]
@djkormo seems to be the most active and keen to keep pushing adcs-issuer forward. I Vote his repo.

**Comment by dimatha** [comment]
> @djkormo seems to be the most active and keen to keep pushing adcs-issuer forward. I Vote his repo.

Agree!

**Comment by djkormo** [comment]
After so many months I prepared documentation at https://djkormo.github.io/adcs-issuer/. Helm chart version of this plugin is now available.

**Comment by wallrj** [comment]
> After so many months I prepared documentation at https://djkormo.github.io/adcs-issuer/. Helm chart version of this plugin is now available.

Great! Open a PR to update https://cert-manager.io/docs/configuration/issuers/  and ping me when you want a review.
* https://github.com/cert-manager/website/blob/07a6456a0ba9fddef0eab4ff92a2caf67268f46a/content/docs/configuration/issuers.md#L9-L29

**Comment by djkormo** [comment]
https://github.com/cert-manager/website/pull/1369

**Comment by inteon** [comment]
I think this has been fixed in https://github.com/cert-manager/website/pull/1369
