### ISSUE TITLE
v1.12 release date is wrong

### ISSUE THREAD

**Issue by shazib-summar** [cert-manager/website#1233]
The release date for v1.12 on the website is wrong. Currently its "May 19, 2024" when it should be "May 19, 2023" ([ref](https://github.com/cert-manager/cert-manager/releases/tag/v1.12.0)).

**Comment by shazib-summar** [comment]
Just to clarify the EOL date for v1.10 also seems wrong. 

<img width="352" alt="image" src="https://github.com/cert-manager/website/assets/27294025/3f836175-7fb5-4ebd-ba7c-70a3fa890f06">


I think this should be May 19, 2023 as well. Is my assumption correct?

**Comment by shazib-summar** [comment]
@inteon what about the eol date for 1.10?

**Comment by inteon** [comment]
its wrong too
