### ISSUE TITLE
Add index job on updating the website

### ISSUE THREAD

**Issue by meyskens** [cert-manager/website#124]
Currently our search index updates every 12 hours in a Prowl job.
We should be looking into leveraging Netifly webhooks in order to run a new index job whenever our website is updated. This will be especially useful when releasing a new version where it needs to create a whole new index for the versions.

**Comment by munnerz** [comment]
Done and visible here: https://testgrid.k8s.io/jetstack-cert-manager-website#cert-manager-website-update-index
