### ISSUE TITLE
Documenting repo management process

### ISSUE THREAD

**Issue by munnerz** [cert-manager/website#154]
Since we have updated the way we handle branching in this repository, we should add a page to the docs on how everything works in this repository.

Roughly:

* All typos/docs changes that are relevant to the 'current' and future releases are made against `master`
* Changes for the *next* release are always made against `release-next`
* We periodically merge `master` into `release-next`
* When releasing version `v0.X`, we:
  * create branch `release-0.(X-1)` by branching from `master`
  * merge `master` into `release-next` one final time
  * update config on release-next to include the `release-0.(X-1)` branch (and any other changes required)
  * merge `release-next` into `master`

From there, the process repeats.

This process means that:

* `master` is always the currently published version of the docs
* `release-next` is always the docs for the *next* version of the docs
* `release-0.X` contains 'old' documentation versions and merges to these branches is ~never done (unless there's some exceptional circumstances that require it)

**Comment by meyskens** [comment]
We should also add a link to update docsearch

**Comment by SgtCoDFish** [comment]
This has totally changed since this issue was raised.

The only important branches now are master and release-next. I'll raise a PR to document that in the README of the website (it's mentioned in the release process but not in the website README). Will close this straight away.
