### ISSUE TITLE
Kubernetes - Air-gapped installation

### ISSUE THREAD

**Issue by jacktar283** [cert-manager/website#163]
Is there any documentation describing how to install cert-manager in an air-gapped environment? ie. With no direct connection to internet.

From what I can make out the Kubernetes installation seems to require 3 containers (quay.io/jetstack/cert-manager-{controller,webhook,cainjector}), but is that all? Are there any other pre-requisites or dependencies that need to be downloaded?

**Comment by munnerz** [comment]
You will also need to include the `acmesolver` image, and set the `--acme-http01-solver-image` flag on the `controller` deployment: https://github.com/jetstack/cert-manager/blob/858cff0f46edece107ba44a0cd27962825e007be/cmd/controller/app/options/options.go#L249-L251

Hope that helps!

**Comment by initdude** [comment]
any one has same experience with air-gapped env? i stuck in this and comminucation between certmanager and webhook is not handshake well
