### ISSUE TITLE
Kubernetes Installing with regular manifests section is missing challenge resources

### ISSUE THREAD

**Issue by mdroogendijk** [cert-manager/website#171]
In the documentation on https://cert-manager.io/docs/installation/kubernetes/#installing-with-regular-manifests is stated:

Installing with regular manifests

All resources (the CustomResourceDefinitions, cert-manager, namespace, and the webhook component) are included in a single YAML manifest file:

However, the yaml file appears to be missing the CRD's related to challenges, causing the cert-manager to log numerous messages like:

`E0410 08:47:15.780099       1 reflector.go:153] external/io_k8s_client_go/tools/cache/reflector.go:105: Failed to list *v1alpha2.Challenge: the server could not find the requested resource (get challenges.acme.cert-manager.io)`

This is noticed when trying to issue a letsencrypt-staging certificate.
If I rebuild the environment and apply the listed crds file (https://github.com/jetstack/cert-manager/releases/download/v0.14.1/cert-manager.crds.yaml) in the Helm section beforehand, everything works perfectly.

Can either the documentation on regular manifests installtion or the yaml file used in that section be updated so it works after following the listed steps?

**Comment by meyskens** [comment]
I just ran the static manifests and it does seem to deploy the CRDs correct

Can you post the output you see when applying the static manifest?
```
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.14.2/cert-manager.yaml
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io configured
[...]
```

**Comment by mdroogendijk** [comment]
I tried recreating the issue myself but don't seem to be able to. I guess we can ignore it and focus on other things.
