### ISSUE TITLE
Order of versions of cert-manager in menu

### ISSUE THREAD

**Issue by maxdaniel98** [cert-manager/website#178]
Could we change the order of this versions menu to be correct? Latest version is now below the before-last version. 

![image](https://user-images.githubusercontent.com/1595178/79639246-d2c7c980-818a-11ea-8d9a-fb3da37705a2.png)

**Comment by meyskens** [comment]
Technically v0.14 is still the latest version as v0.15 is alpha. But I get your point, we should somehow label the pre-releases better to avoid confusions. cc @munnerz any suggestions on this?

**Comment by inteon** [comment]
@SgtCoDFish Thank you for fixing this issue
<img width="140" alt="image" src="https://user-images.githubusercontent.com/42113979/218692386-ace0bf67-84c4-42ae-81f5-915612260510.png">
