### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by munnerz** [cert-manager/website#198]
Quick notes/thoughts:

- Merge 'master' of cert-manager/website into 'release-next'
- PR release notes to documentation site
- Update version numbers on documentation site
- Ensure CI config in jetstack/testing is up to date
- Fast forward release branch
- Stage the new version with cmrel
- Publish the new version with cmrel
- Update `jetstack/cert-manager-olm`: https://github.com/jetstack/cert-manager-olm/pull/7
- Trigger build in Red Hat portal
- Merge 'release-next' into 'master'
- PR to docsearch with the new version/index

/kind documentation

**Comment by wallrj** [comment]
More important than ever I think.
Next release, me and / or @hzhou97 should shadow @meyskens and help document the process.

/assign @meyskens 
/priority important-soon

**Comment by inteon** [comment]
Available here: https://cert-manager.io/docs/contributing/release-process/
