### ISSUE TITLE
`cert-manager` URL shown in the document is incorect

### ISSUE THREAD

**Issue by rachasakr** [cert-manager/website#212]
In [the page `Kubectl plugin`,  section `Installation`](https://cert-manager.io/docs/usage/kubectl-plugin/#installation), there're commands to install `kubectl-cert-manager.tar.gz` using the released file from Github. However, the URL for the file using in the page is incorrectly spell `cert-manager-liux` instead of `cert_manager-linux`. So, when a user tries to use `curl` command from the page, the file content will be "Not Found" instead of the actual program.

I've already forked this repo and fix the issue. Please see the PR. 

Thanks

**Comment by rachasakr** [comment]
Also, for some reason I'm too lazy to find it out, Github doesn't serve the file directly. When using `curl` without `-L` (follow redirect) option, the file returns from `curl` will be an HTML code for redirection instead of the file. So, to solve this issue, I also introduce that option into the command.

I've tested the command and now it's working just fine.

Again, please check my PR.

**Comment by meyskens** [comment]
Closing this as the PR is merged
