### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by jdw2465** [cert-manager/website#219]
Would love to contribute as a tech writer; noticed in this topic some typos, but have lots of suggestions in other ways that can help other users and contributors. 

" . . . using cert-manager however, **set**-by-step tutorials are very useful . . ."

**Comment by meyskens** [comment]
Hey @jdw2465 

All contributions welcome! There is a log going on in the cert-manager channel in slack.k8s.io if you need inspirartion

**Comment by wallrj** [comment]
Thanks @jdw2465 It would be great if you could help us improve our documentation.
Please create PRs here or in the https://github.com/jetstack/cert-manager repo (as appropriate) and we'll review them.
I'll close this issue now.

/kind documentation
/close
