### ISSUE TITLE
Documenting resolution for DigitalOcean + HTTP01 "connection timed out" error

### ISSUE THREAD

**Issue by munnerz** [cert-manager/website#229]
Copied across from: https://github.com/jetstack/cert-manager/issues/2744

> Ok, found the issue. The DigitalOcean tutorial is missing an important step: https://www.digitalocean.com/community/questions/how-do-i-correct-a-connection-timed-out-error-during-http-01-challenge-propagation-with-cert-manager

> You must add your domain to the nginx-ingress service.

**Comment by SgtCoDFish** [comment]
This is so old I'm just gonna close it. If it were on the cert-manager repo it would already have been closed for being rotten
