### ISSUE TITLE
Namespace discrepancy in kube-lego migration guide

### ISSUE THREAD

**Issue by kcranston** [cert-manager/website#235]
In the [kube-lego migration guide](https://cert-manager.io/docs/tutorials/acme/migrating-from-kube-lego/), step 2 points you to the [cert-manager installation instructions](https://cert-manager.io/docs/installation/kubernetes/#steps), which start with creating a `cert-manager` namespace. When you go back to the migration guide, steps 3-5 assume you have installed cert-manager into `kube-system`, e.g.:

> Once done, we need to create this new resource in the kube-system namespace. By default, cert-manager stores supporting resources for ClusterIssuers in the namespace that it is running in, and we used kube-system when deploying cert-manager above. You should change this if you have deployed cert-manager into a different namespace. 

It would be good to have both the installation guide and migration guide use the same namespace, or to change the namespace in the migration guide to a `where-you-installed-cert-manager` variable.

**Comment by meyskens** [comment]
I think this guide got outdated, oops.... a PR to change kube-system to `cert-manager` is more than welcome!

**Comment by hzhou97** [comment]
[PR](https://github.com/cert-manager/website/pull/238) by @meyskens fixed it.
/close
