### ISSUE TITLE
[DOCS]: Add info on how to customize kind CertManager when using OperatorHub method on Openshift

### ISSUE THREAD

**Issue by rajinator** [cert-manager/website#262]
Documentation for using cert-manager via Operatorhub on OKD/OCP clusters is very limited. There are times when customization of the deployment is needed.

Case in point, one of the clusters I have, requires the use of recursive nameservers as described here - https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check. However, when modifying the deployment to include the arg, the operator will overwrite the deployment yaml file.

The apiresources Schema description does not provide any info, as seen in this screenshot below
![image](https://user-images.githubusercontent.com/26853703/88447113-c55f5280-cdfd-11ea-8e93-313bd604f72c.png)

Environment details:

OCP 4.3.29
Cloud-provider/provisioner (e.g. GKE, kops AWS, etc): KVM
cert-manager version (e.g. v0.4.0): v0.15.2
Install method (e.g. helm or static manifests): OperatorHub
Would like to see more details https://cert-manager.io/docs/installation/openshift/#installing-with-cert-manager-operator
Also a link to the CRD for kind CertManager would be helpful as well. Apologies if this has been already documented somewhere

/kind feature

Creating issue here as per @meyskens request :)

**Comment by meyskens** [comment]
Thanks for making the issue here!

**Comment by rajinator** [comment]
Hi @meyskens! Anything new for this? no snark intended :)

**Comment by maelvls** [comment]
Hi,

The documentation for OLM was updated by Richard in May 2022 (https://github.com/cert-manager/website/pull/983). The changes are visible here: https://cert-manager.io/docs/installation/operator-lifecycle-manager/

I'll close this issue for now; please let me know if it is still an issue and I'll re-open it.
