### ISSUE TITLE
pull-cert-manager-website-verify is pulling stale data from other branches.

### ISSUE THREAD

**Issue by TBBle** [cert-manager/website#273]
Reference: https://github.com/cert-manager/website/pull/272#issuecomment-667080023

It seems that the pull-cert-manager-website-verify job, when trying to verify a PR against the master branch, is seeing a not-the-most-recent commit on the release-next branch, and failing the build because of it.

Specifically, I'm seeing this failure report in [the logs](https://storage.googleapis.com/jetstack-logs/pr-logs/pull/cert-manager_website/272/pull-cert-manager-website-verify/1289152900248899584/build-log.txt):
```
+++ Running spell check
    content/en/next-docs/installation/compatibility.md
       36 | n a custom CNI on EKS, so the CNIs differ between control 
       43 | Note that since kubelet uses port `10250` by default  

>> 2 spelling errors found in 536 files
```

which was caused by 9d485d0a4cdf263add370542c68cd3bc93c65ee9 (same errors appear in [the build log for this commit](https://storage.googleapis.com/jetstack-logs/pr-logs/pull/cert-manager_website/268/pull-cert-manager-website-verify/1288388968919863296/build-log.txt)) and fixed by a6c70fa59b05b8500391823e073051dac18dd4ec 10 hours later, both on release-next, both part of the same PR (#268), which was merged four hours ago, and itself passed the same job.

The pull-cert-manager-website-verify jobs doesn't appear to log the hash it found on the branches it pulls, so it's not clear what's going on here.

I retried the job an hour later, with the [same result](https://storage.googleapis.com/jetstack-logs/pr-logs/pull/cert-manager_website/272/pull-cert-manager-website-verify/1289166668974526464/build-log.txt).

It looks like this is the [first run of this job](https://prow.build-infra.jetstack.net/job-history/gs/jetstack-logs/pr-logs/directory/pull-cert-manager-website-verify) since #268 was merged, in case somehow #268 left the tree in a bad state, despite passing its own builds...

**Comment by meyskens** [comment]
It took me a morning coffee to understand but the issue here is not stale data it is that we take the `.spell` from `master` merged with the PR branch. But since we added new correct words to release-next we never added them on `master`. 

Is fixed in https://github.com/cert-manager/website/pull/274
