### ISSUE TITLE
Update examples to v1beta1 API

### ISSUE THREAD

**Issue by alexbrand** [cert-manager/website#277]
There's a couple of places that use the v1alpha2 API instead of the v1beta1 API.

* https://cert-manager.io/docs/usage/certificate/
* https://cert-manager.io/docs/configuration/selfsigned/
* https://cert-manager.io/docs/configuration/ca/
* https://cert-manager.io/docs/configuration/vault/

Looks like most examples are actually showing the old APIs. Is the v1beta1 not the preferred API?

**Comment by meyskens** [comment]
This is on purpose as the v1alpha1 API is the only API version that works for Kubernetes 1.14 and below, using v1beta1 in the examples would break it for them. This will soon change when we release the v1 API however.

/close
