### ISSUE TITLE
Document where to place secret for CA-type ClusterIssuer

### ISSUE THREAD

**Issue by alexbrand** [cert-manager/website#278]
The CA-type issuer references a kubernetes secret that contains the private key for signing. When creating an Issuer, it is assumed that the secret exists in the same namespace as the Issuer. However, when using a ClusterIssuer, where to place the CA secret is unclear.

After digging around in the code and other issues, it seems like the Secret must live in the same namespace as the cert-manager controller.

**Comment by JoshVanL** [comment]
This is clearly labeled in the documentation.

https://cert-manager.io/docs/faq/cluster-resource/

**Comment by alexbrand** [comment]
Ah! I have no idea why that page escaped me. I wonder if it's worth linking to that from the Configuration page? https://cert-manager.io/docs/configuration/ If not, feel free to close this out. Thanks!

**Comment by JoshVanL** [comment]
No worries :slightly_smiling_face: 

You're right. That fact you didn't find it means it's not fit for purpose. I'll open up a PR.

/assign
