### ISSUE TITLE
Document upgrade path for legacy users of v1.0

### ISSUE THREAD

**Issue by meyskens** [cert-manager/website#283]
Upgrading to the v1 API with cert-manager v1.0 should be documented for legacy users.
The document should also emphasis that upgrading to Kubernetes 1.16+ might be a better idea.

It should document:
* how to safely upgrade the controllers
* how to upgrade the stored resources using our CLI (can be reused for others too to update infra as code!) 

Preferably this is written when we have a beta release

**Comment by SgtCoDFish** [comment]
I'm gonna close this - I think most likely anyone who's this out of date now is better off just starting fresh with the latest version of cert-manager. We get the occasional question on this kind of thing but it tends to end in people just uninstalling and starting fresh
