### ISSUE TITLE
Update cert-manager compatibility guarantees

### ISSUE THREAD

**Issue by wallrj** [cert-manager/website#305]
In https://github.com/cert-manager/website/pull/303/files#r479211622 @meyskens  wrote:
> This is not true any longer due to OpenShift 3.11 being supported for 4 years we somehow are also bound to that. Should be made into an issue to be handled later

So we need to update that information at https://cert-manager.io/docs/concepts/project-maturity/

**Comment by SgtCoDFish** [comment]
This is obsoleted by #563, so I'm gonna close this issue in favour of that one
