### ISSUE TITLE
Case for CertificatePrivateKey (encoding, algorithm) is wrong (v1)

### ISSUE THREAD

**Issue by jr0d** [cert-manager/website#330]
Greetings!

The documentation states that:
 
PrivateKeyEncoding:
> allowed values are “pkcs1” and “pkcs8” standing for PKCS#1 and PKCS#8

PrivateKeyAlgorithm:
> allowed values are either “rsa” or “ecdsa” 

However, allowed values are uppercase, PKCS1/PKCS8 and RSA/ECDSA respectively. The change seems to have been added in v1beta1. 

```
 > k apply -f test-cert.yaml
The Certificate "test-certificate" is invalid:
* spec.privateKey.algorithm: Unsupported value: "rsa": supported values: "RSA", "ECDSA"
* spec.privateKey.encoding: Unsupported value: "pksc1": supported values: "PKCS1", "PKCS8"
```

**Comment by meyskens** [comment]
This changed in v1.0 indeed, PRs are welcome!

**Comment by inteon** [comment]
This has been fixed, see https://github.com/cert-manager/website/blob/8ccd9cb0f5c695c76abf952b26d77a808d59a41f/content/docs/reference/api-docs.md?plain=1#L3874/.
