### ISSUE TITLE
Clearly reference a Custom Resource Definition (CRD) in the documentation

### ISSUE THREAD

**Issue by Luttik** [cert-manager/website#334]
Hi, 

For validation and autocompletion in IDE's It would be very useful to give the [cert-manager.crds](https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.crds.yaml) a more prominent place in the documentation. 

This is especially relevant for projects where a helm chart indirectly requires cert-manager resources. I feel like this is mainly beneficial since dependencies between big helm projects and Kubernetes resources can be very opaque.

**Comment by meyskens** [comment]
Never had a IDE that understood a CRD, if you have more info on how to set that up a PR is more than welcome

**Comment by Luttik** [comment]
Im not sure if it is pycharm or the [cloud code](https://cloud.google.com/code) plugin (which is adviced in googles GKE tutorials). But all you have to do is link to the crd yaml (which i linked in the previous comment) and the pycharm will autocomplete your yaml instances of thr custom resource. If it is part of the plugin rather than pycharm it will probably also work in vscode.

**Comment by meyskens** [comment]
They are already present in our installation: https://cert-manager.io/docs/installation/kubernetes/#steps

Is there a preferred place where they would be good to find?

**Comment by Luttik** [comment]
Oh sorry. I guess that should be logical... I just completely missed it.
