### ISSUE TITLE
SVG Broken

### ISSUE THREAD

**Issue by meyskens** [cert-manager/website#369]
The rendering of the cert-mamager SVG logo seems to be broken on recent rendering engines like Chrome beta or some releases of Firefox.

**Comment by jakexks** [comment]
We need to ask the artist for a copy of the original, and consider using a PNG version on the website
/kind design
/priority important-soon

**Comment by mattbates** [comment]
cc @munnerz

**Comment by jakexks** [comment]
This appears to have un-broken on recent Chrome/ium but is still broken on Safari

**Comment by maelvls** [comment]
Here is the illustrator file, we can use it to re-generate a new SVG blob:
[Cert Manager Stamp Final.ai.zip](https://github.com/cert-manager/website/files/6095263/Cert.Manager.Stamp.Final.ai.zip)

**Comment by maelvls** [comment]
I could not open the `.ia` file so I use convertio.co to convert it into SVG, and then I fixed the bounding box to perfectly fit the logo:
[Cert-Manager-Stamp-Final.svg.zip](https://github.com/cert-manager/website/files/6095308/Cert-Manager-Stamp-Final.svg.zip)

It looks like this:
![svg-to-png](https://user-images.githubusercontent.com/2195781/110206990-624c9880-7e81-11eb-8164-c25fb207f9fc.png)

**Comment by maelvls** [comment]
@munnerz  I noticed the `.ai` file seems to only contain a single layer with a raster image. I opened the file using Adobe Illustrator 25.2.

Weird, the same file can be converted from `.ai` to SVG on https://convertio.co, but I can't open it on Adobe Illustrator itself 😞 

![illustrator](https://user-images.githubusercontent.com/2195781/110212522-fcb9d580-7e9b-11eb-92fe-02d595d7cc92.png)

**Comment by maelvls** [comment]
In the end I was able to open the SVG file that https://convertio.co gave me in Inkscape:

![inkscape](https://user-images.githubusercontent.com/2195781/110213512-aa2ee800-7ea0-11eb-89b0-e804f641d8cc.png)

I fixed the background issue by adding a `#ffffff` circle in a background layer:

![new-svg-screenshot-cert-manager-website](https://user-images.githubusercontent.com/2195781/110213504-a4d19d80-7ea0-11eb-8e98-1b4439813908.png)

**Comment by maelvls** [comment]
before vs. after:
<img alt="before" src="https://user-images.githubusercontent.com/2195781/110213818-fcbcd400-7ea1-11eb-939b-38cf14c7fc14.png" width="300"/>
<img alt="after" src="https://user-images.githubusercontent.com/2195781/110213820-fdee0100-7ea1-11eb-8003-0646b58322da.png" width="300"/>
