### ISSUE TITLE
Edit link is broken

### ISSUE THREAD

**Issue by maelvls** [cert-manager/website#384]
While trying to add some information about using the `WIP:` PR title prefix, I noticed that the "Edit" link [on that page](https://cert-manager.io/next-docs/contributing/contributing-flow/) was broken.

```
Got:      https://github.com/cert-manager/website/edit/master/content/en/next-docs/contributing/contributing-flow.md
Expected: https://github.com/cert-manager/website/edit/master/content/en/docs/contributing/contributing-flow.md
```

How can I help to fix this, e.g. to change `/next-docs/` to `/docs/`?

**Comment by meyskens** [comment]
I think this is a limitation in the hugo system which we use, would be happy to see that fixed but it would need to be aware of version branches too which the edit link right now is not

**Comment by maelvls** [comment]
Weird, this issue seems to have disappeared... Now when I click on "Edit this page" I get something like

```
https://github.com/cert-manager/website/edit/master/content/en/docs/release-notes/release-notes-1.1.md
```

🙏
