### ISSUE TITLE
Restore Procedure: Prevent Cert Re-order

### ISSUE THREAD

**Issue by chainlink** [cert-manager/website#397]
When restoring, if i install cert manager first before applying the backed up resources, it tries to re-issue certs for ingresses present on the cluster.

Backup:
Add step to backup certificate secrets - _Is it better to backup these secrets, or let LE re-issue?_

I think the restore procedure should be:
1. Restore CRDs
2. Restore (cleaned) backup (see #234)
3. Install Cert manager

Thoughts? Happy to PR the change to the docs if this makes sense

**Comment by meyskens** [comment]
> Is it better to backup these secrets, or let LE re-issue?

Probably better to backup the secrets too unless you think the storage medium of your backups is compromised/easy to infiltrate. 
It will allow to:
- restore certificates before everything us online to solve the ACME challenges
- not hit the LE rate limits

If you are sharing the backup on something like a Git repo, Slack, shared computer,... I would avoid it as it will leak your private key.

**Comment by wallrj** [comment]
Thanks for the bug report @chainlink 

I'm going to close this issue in favour of another more general issue about improving the Backup and restore instructions 
 * https://github.com/cert-manager/website/issues/234

If you have time to contribute some improved documentation  as a PR we'd be most grateful and I'll help review and test it.

/close
