### ISSUE TITLE
Upgrading - page ordering is not great

### ISSUE THREAD

**Issue by strigona-worksight** [cert-manager/website#41]
https://cert-manager.io/docs/installation/upgrading/

I would expect the v0.11 to v0.12 item to be above the v0.10 to v0.11 entry.
![Screenshot from 2019-11-28 08-46-57](https://user-images.githubusercontent.com/13368604/69822684-d8ad1600-11bb-11ea-943f-46f8253446f0.png)

**Comment by munnerz** [comment]
#43 fixes this 😄
