### ISSUE TITLE
v1.1 doc points to top of trunk and v1.2 doc points to actual v1.1 documentation

### ISSUE THREAD

**Issue by Jean-Daniel** [cert-manager/website#429]
I think that the documentation "v1.1" and "v1.2" version selector items are inverted.

For instance, when choosing the v1.1 doc, I get the install instruction for non existing v1.2 and when choosing v1.2 I get the v1.1 install instruction.

Moreover, the items are not in the right order in the menu:

<img width="238" alt="Capture d’écran 2021-02-07 à 18 11 37" src="https://user-images.githubusercontent.com/304649/107153867-1127b280-6970-11eb-8b08-62752aa70be9.png">

**Comment by meyskens** [comment]
Fixed in https://github.com/cert-manager/website/pull/430
