### ISSUE TITLE
Prepare the 1.2 release

### ISSUE THREAD

**Issue by maelvls** [cert-manager/website#431]
We aim at releasing cert-manager 1.2 tomorrow (11 Feb 2021 at 9:30 UK time).

As part of this release, we need to:

- [x] @maelvls  create the upgrade document, → done in https://github.com/cert-manager/website/pull/432 but wrong base branch!
- [ ] @jakexks update the mentions of `1.1` to `1.2` in `curl` install commands on the website.
- [x] @maelvls  re-create https://github.com/cert-manager/website/pull/430 and get it ready for the release party → done in #433  but wrong base branch!
- [x] Copy paste the "⚠️ NOTICE" from https://github.com/cert-manager/website/pull/430 to the release notes while we do the release party:
     > From cert-manager `v1.2.0` onward, the minimum supported version of Kubernetes is `v1.16.0`. Users still running Kubernetes `v1.15` or below should upgrade to a supported version before installing cert-manager or use cert-manager `v1.1`.
- [x] Copy paste the "⚠️ DEPRECATION" from https://github.com/cert-manager/website/blob/release-next/content/en/docs/release-notes/release-notes-1.2.md to the release notes while we do the release party:
     > The `--renew-before-expiration-duration` flag of the cert-manager controller-manager has been deprecated. Please set  the `Certificate.Spec.RenewBefore` field instead. This flag will be removed in the next release.
    (but it should have been already added to the release notes since the issue contains `action required`)
- [x] Add a "BREAKING CHANGE" about the user agent change

To be done after releasing:
- [x] @jakexks Merge cert-manager/website `release-1.2` into master → https://github.com/cert-manager/website/pull/434

For later:
- [ ] Merge the notes we took during the 1.2 release party → https://github.com/cert-manager/website/pull/435

**Comment by JoshVanL** [comment]
Now that the helm issue is resolved, I don't think we have any special notes for it. Hopefully we can use the same notes from here :smile: 

https://cert-manager.io/docs/installation/upgrading/upgrading-1.0-1.1/

**Comment by maelvls** [comment]
I'll add the upgrade doc then, seems quite easy 😅

@jakexks Do you want to update the references in `curl` commands and such on the website?

**Comment by maelvls** [comment]
@jakexks do you know how I can create a `release-1.2` branch? I don't have any privilege here :(
