### ISSUE TITLE
Documentation OpenShift - Broken link (Cert manager)

### ISSUE THREAD

**Issue by migounette** [cert-manager/website#436]
```
On OpenShift 4 you can also install **cert-manager** via the OperatorHub using the cert-manager operator, this can be found under Red Hat OpenShift Certified Operators in the Embedded OperatorHub of your OpenShift installation. Any values set in the Operator configuration get passed through as Helm values.
```

cert-manager is set to https://catalog.redhat.com/software/operators/detail/5e999d862937381642a21c7a
and 
should be https://catalog.redhat.com/software/containers/search?q=cert-manager&p=1

**Comment by irbekrm** [comment]
Hi @migounette thanks for spotting that! Would you be interested to PR the fix 😄 ?

**Comment by rbaumgar** [comment]
I am not able to find the right link...

**Comment by irbekrm** [comment]
This should be done soon, to avoid confusion.

/priority imporant-soon

**Comment by migounette** [comment]
Back to my issue... sorry for the delay...
I can provide you the good link but it may be necessary to point to one of the JetStack existing package

![image](https://user-images.githubusercontent.com/1232978/115107042-c2e2f100-9f68-11eb-80d6-1613f487edf7.png)
