### ISSUE TITLE
cert manager is no longer on the OpenShift operator list

### ISSUE THREAD

**Issue by rbaumgar** [cert-manager/website#459]
under "Installing with cert-manager operator"
https://cert-manager.io/docs/installation/openshift/#installing-with-cert-manager-operator
the link https://catalog.redhat.com/software/operators/detail/5e999d862937381642a21c7a --> not found

https://catalog.redhat.com/software/operators/search?q=cert-manager&p=1 --> no result

**Comment by jakexks** [comment]
Related: https://github.com/cert-manager/website/issues/436

I'll take a look at this as a part of upgrading the Openshift release to v1.2

/assign

**Comment by irbekrm** [comment]
Has this been fixed now?

I am not sure if there is any way for us to verify that as we don't have access to an admin panel (as we don't have an openshift login)

**Comment by erikgb** [comment]
This is what I see when I search for "cert-manager" in the OpenShift console in one of our clusters:

![image](https://github.com/user-attachments/assets/db42c18d-f41c-42c8-b7d9-d03f69172815)

I cannot find the referenced broken link in the documentation anymore. I suggest closing this issue now. WDYT?
