### ISSUE TITLE
update Ingress API version in the examples.

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/website#468]
There are a few code examples (i.e [here](https://cert-manager.io/docs/tutorials/acme/ingress/#step-4-deploy-an-example-service)) in the `cert-manager` website that use the `extensions/v1beta1` API which is deprecated. 

We should update the examples to use `networking.k8s.io/v1` instead and make sure they work with the new API (for example `ingress.spec.rules.http.paths.backend.serviceName` is now `ingress.spec.rules.http.paths.backend.service.name`)

Could check for other deprecated APIs too.

**Comment by adedejisalim** [comment]
I would like to try this Issue.

**Comment by irbekrm** [comment]
Hi @adedejisalim ,

Glad you are interested in contributing! 
Let us know if you have any questions and feel free to `/assign` yourself to this 😄

**Comment by irbekrm** [comment]
This has now been implemented by #472  and #476.
