### ISSUE TITLE
Docs imply hosts is optional but it isn't

### ISSUE THREAD

**Issue by gerrywastaken** [cert-manager/website#475]
> tls: # < placing a host in the TLS config will indicate a certificate should be created
https://github.com/cert-manager/website/blame/59df6949822a40319fb0521662f897b2260007a9/content/en/docs/usage/ingress.md#L40

This implies that you can just specify a TLS config without a host, perhaps for an pre-generated cert. However when trying this you get the following error:

```
> kubectl describe ingress web
[...]
Warning  BadConfig  3m11s (x2 over 3m11s)  cert-manager              TLS entry 0 is invalid: secret "web-crt" for ingress TLS has no hosts specified
```

This is expected if you read the [ingress docs](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls), but this comment in the cert-manager docs is quite misleading.

**Comment by gerrywastaken** [comment]
This is much better. Thank you for making the change. :D

**Comment by SgtCoDFish** [comment]
And thank you for raising this for our attention :grin:
