### ISSUE TITLE
Helm Repo no longer valid - https://charts.jetstack.io

### ISSUE THREAD

**Issue by ashfondu** [cert-manager/website#478]
I am trying to install cert-manager using your instructions and it seems like the repo location (https://charts.jetstack.io) is no longer valid or deprecated. 

the cert-manager helm chart at https://charts.helm.sh/stable also doesnt work anymore since it uses deprecated references to deployments apps/v1beta1

Can you update these instructions with a working / updated repo. 
Thanks

https://github.com/cert-manager/website/blob/master/content/en/docs/installation/kubernetes.md

**Comment by maelvls** [comment]
Hi!

> it seems like the repo location (https://charts.jetstack.io) is no longer valid or deprecated

You are right, the root (`/`) at https://charts.jetstack.io is giving nothing (as seen in the below screenshot). This is a bug we are currently working on in https://github.com/jetstack/cert-manager/issues/3513.

<img alt="artifacthub shows an empty page when looking for the charts of the cert-manager organization" src="https://user-images.githubusercontent.com/2195781/114386089-0f0cea80-9b91-11eb-8864-2b4b68fa9c0e.png" width="400">

Note that although the `/` path returns a 404, the Helm repository still works as intended:

```sh
% curl -s https://charts.jetstack.io/index.yaml | head
apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2021-04-08T10:25:37.462Z"
    description: A Helm chart for cert-manager
    digest: 97cde67c22602d4a2a5e41b67782fac9d35456584e5388b4ab8f8ac700221e32
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
```

> the cert-manager helm chart at https://charts.helm.sh/stable also doesnt work anymore since it uses deprecated references to deployments apps/v1beta1

The `stable` Helm repo has been deprecated. We invite people using https://charts.jetstack.io instead.

**Comment by maelvls** [comment]
Feel free to re-open if you feel the issue still exists.

/close
