### ISSUE TITLE
Secret gets UID added to end of name

### ISSUE THREAD

**Issue by dash042** [cert-manager/website#480]
I am unsure if this is a Azure problem, but the secret name which stores the generated certificate keeps getting a UID added to its name (automatically) - which leads to the Traefik Ingress not finding the certificate.

How can I check if my ACME-LetsEncrypt clusterissuer is working fine? Because it seems like it is not.

**Comment by irbekrm** [comment]
Hi, there is a temporary secret created for a Certificate with the private key of the cert to be issued.

That secret is named `<your-specified-secret-name>-<random-uid>`.

Could it be the case that you are looking at the temporary secret?

**Comment by irbekrm** [comment]
Closing as this likely refers to the temporary secret created during issuance.
