### ISSUE TITLE
CA Injector - missing documentation for inject-ca-from?

### ISSUE THREAD

**Issue by adrianludwin** [cert-manager/website#50]
According to Google, this page used to have documentation for `cert-manager.io/inject-ca-from` but now it just says:

> This component is configured using the cert-manager.io/inject-apiserver-ca: "true" and cert-manager.io/inject-apiserver-ca: "true" annotations on the ValidatingWebhookConfiguration and MutatingWebhookConfiguration resources.

Note that it documents `inject-apiserver-ca` twice. Is the second reference supposed to be to `inject-ca-from`?

**Comment by dsbrng25b** [comment]
@adrianludwin This got fixed in https://github.com/cert-manager/website/commit/c52d477e2e8e5407ffe21881685eb65907148cc3#diff-75148ae39540c4cc1d7d8ded0a277d7d

**Comment by adrianludwin** [comment]
Thanks!
