### ISSUE TITLE
Create a page "Conformance criteria for external issuers who want to join the cert-manager org"

### ISSUE THREAD

**Issue by maelvls** [cert-manager/website#501]
As discussed [on 24 March 2021](https://docs.google.com/document/d/1Tc5t6ylY9dhXAan1OjOoldeaoys1Yh4Ir710ATfBa5U/edit#bookmark=id.clt8q51e85nk), we want to be formalizing our requirements for an external issuer to become "certified" (not sure the term is right). I was thinking about following HashiCorp's idea of having a [Conformance tests](https://www.terraform.io/docs/extend/testing/index.html#acceptance-tests) page that lists how to run the conformance tests in order to have their external Terraform provider listed onto the [Terraform Registry](https://registry.terraform.io/browse/providers).

As far as I know, the only external issuer that runs our conformance tests suite is the [sample-external-issuer](https://github.com/cert-manager/sample-external-issuer). Unfortunately, the way we run the conformance tests for it is highly tied to the cert-manager codebase. The sample issuer is set up in [setup-e2e-deps.sh](https://github.com/jetstack/cert-manager/blob/5dd00bf2a5ced6d5315ca7f7c8d4733aea891703/devel/setup-e2e-deps.sh#L55-L56):

```sh
echo "Installing sample-external-issuer into the cluster..."
"${SCRIPT_ROOT}/addon/sample-external-issuer/install.sh"
```

and the code for the actual conformance test is in [external.go](https://github.com/jetstack/cert-manager/blob/dffbf391dbb0fc6c1cfea62e561a9c6f54362ab0/test/e2e/suite/conformance/certificates/external/external.go#L41-L62):

```go
var _ = framework.ConformanceDescribe("Certificates", func() {
	unsupportedFeatures := featureset.NewFeatureSet(
		featureset.DurationFeature,
		featureset.KeyUsagesFeature,
		featureset.SaveCAToSecret,
	)

	issuerBuilder := newIssuerBuilder("Issuer")
	(&certificates.Suite{
		Name:                "External Issuer",
		CreateIssuerFunc:    issuerBuilder.create,
		UnsupportedFeatures: unsupportedFeatures,
	}).Define()

	clusterIssuerBuilder := newIssuerBuilder("ClusterIssuer")
	(&certificates.Suite{
		Name:                "External ClusterIssuer",
		CreateIssuerFunc:    clusterIssuerBuilder.create,
		DeleteIssuerFunc:    clusterIssuerBuilder.delete,
		UnsupportedFeatures: unsupportedFeatures,
	}).Define()
})
```

The goal of this issue is to discuss a new "Conformance tests" page that will be added to https://cert-manager.io/docs/contributing/external-issuers/.

cc @irbekrm

**Comment by SgtCoDFish** [comment]
# Accepting Third-Party Code into the cert-manager Organization

Example header for document:

```text
The cert-manager project welcomes external contributions and has benefited greatly from thousands
of commits from hundreds of different contributors. Most code is committed through pull requests
to a specific repo, whether that be the main cert-manager repository or one of the associated
repos such as the website.

Some contributions aren't as well suited to that kind of workflow. This document aims to address
such contributions and provide a framework for sustainable contributions which can be tested and
relied upon going forwards.
```

## Requirements

We need to decide which of these must be included. I've marked them with either VITAL, IMPORTANT or MAYBE based on my own evaluation, but which ones we actually include could change based on what the team thinks.

- VITAL: Must be licensed appropriately, both for the code itself and any dependencies it has
- VITAL: Must conform to CNCF standards / due diligence requirements
- VITAL: Must have a sponsor by an existing maintainer
- IMPORTANT: Must pass cert-manager conformance tests
- IMPORTANT: Must provide a point-of-contact for questions about the project valid for at least 3 months after acceptance [1]
- IMPORTANT: Must be a defined extension type (DNS solver, custom issuer, HTTP solver), or else justify why it doesn't belong in the main repos
- IMPORTANT: Must have a similar level of code quality to cert-manager itself (enforced by tooling)
- IMPORTANT: Must have a non-trivial test suite, both unit tests and end-to-end tests
- IMPORTANT: Must adopt the cert-manager security policy and link back to the policy, as in e.g. [the istio-csr `SECURITY.md`](https://github.com/cert-manager/istio-csr/blob/master/SECURITY.md)
- MAYBE: Must have DCO signoffs for all commits in place to ensure the code can legally be donated, or else must have a positive DCO affirmation made by each contributor prior to donation
- MAYBE: Must be written in Go
- MAYBE: Must have boilerplate headers added to source files?

[1] We don't anticipate this would be used much, but it is important to be able to reach someone if required

## Notes

Micah Hausler reached out to `@caniszczyk` in an email about donation and licensing, which is super helpful. See [here](https://github.com/jetstack/cert-manager/issues/3675#issuecomment-821267370)

### CoreDNS Process

[`GOVERNANCE.md`](https://github.com/coredns/coredns/blob/master/GOVERNANCE.md#other-projects)

The CoreDNS organization is open to receive new sub-projects under its umbrella. To accept a project into the CoreDNS organization, it has to meet the following criteria:

- Must be licensed under the terms of the Apache License v2.0
- Must be related to one or more scopes of the CoreDNS ecosystem:
- CoreDNS project artifacts (website, deployments, CI, etc)
	- External plugins
	- Other DNS related processing
	- Must be supported by a Maintainer not associated or affiliated with the author(s) of the sub-projects

The submission process starts as a Pull Request or Issue on the `coredns/coredns` repository with the required information mentioned above. Once a project is accepted, it's considered a CNCF sub-project under the umbrella of CoreDNS.

### Envoy Process

[`GOVERNANCE.md`](https://github.com/envoyproxy/envoy/blob/main/GOVERNANCE.md#adding-new-projects-to-the-envoyproxy-github-organization) links to [`EXTENSION_POLICY.md`](https://github.com/envoyproxy/envoy/blob/main/EXTENSION_POLICY.md).

All extensions contained in the main Envoy repository will be held to the same quality bar as the core Envoy code. This includes coding style, code reviews, test coverage, etc. In the future we may consider creating a sandbox repository for extensions that are not compiled/tested by default and held to a lower quality standard, but that is out of scope currently.

### containerd Process

[`GOVERNANCE.md`](https://github.com/containerd/project/blob/master/GOVERNANCE.md#subprojects)

The containerd process defines a distinction between "core" and "non-core" subprojects.

### Kubernetes Process

[`kubernetes-repositories.md`](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories)

**Comment by irbekrm** [comment]
Looks good to me!

Is it worth adding workflow to requirements? (i.e code must be committed via code reviews & pull requests). You do mention it in the top level comment though.

> Must have a similar level of code quality to cert-manager itself (enforced by tooling)

Does the tooling bit also include that there would have to be some sort of CI set up so there is automated testing on each PR?

Another somewhat code-related thing might be properly versioned/tested releases with an automated release process?

Do you think it is worth also adding something about what are some good reasons why it would make sense for a project to be donated/accepted? (i.e as in the case of AWS issuer to make it easier for the AWS folks to contribute).

Also, would we expect that some community involvement can be predicted? (i.e that it's not a project with just a single maintainer/contributor)?

**Comment by maelvls** [comment]
Thank you @SgtCoDFish for the [third-party code donation](https://cert-manager.io/docs/contributing/third-party-code-donation/) page!! Closing now.
