### ISSUE TITLE
Certificate Resources: keyAlgorithm case in example is wrong

### ISSUE THREAD

**Issue by stephen-dexda** [cert-manager/website#55]
Should be `rsa` not `RSA` - latter fails validation: ` spec.keyAlgorithm in body should be one of [rsa ecdsa]`.

**Comment by munnerz** [comment]
Could you point to where this typo is? Thanks 😄

**Comment by stephen-dexda** [comment]
https://cert-manager.io/docs/usage/certificate/#creating-certificate-resources
