### ISSUE TITLE
Securing NGINX-ingress

### ISSUE THREAD

**Issue by renjithmenon** [cert-manager/website#572]
helm init --service-account=tiller                                                                                   
Error: unknown command "init" for "helm"

Did you mean this?
	lint

Run 'helm --help' for usage.

**Comment by irbekrm** [comment]
Hi,

You probably have Helm `v3` which does not have the `init` subcommand. The ['Install Tiller'](https://cert-manager.io/docs/tutorials/acme/ingress/#step-1-install-tiller) section can be skipped when using Helm `v3`.
