### ISSUE TITLE
Remove Helm v2 from Ingress Nginx tutorial 

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/website#600]
I think the later versions of `cert-manager` don't support Helm v2 so we may want to clean up the Ingress Nginx tutorial https://cert-manager.io/docs/tutorials/acme/ingress/

**Comment by derba** [comment]
I suspect a pull request on https://github.com/cert-manager/website/blob/master/content/en/docs/tutorials/acme/nginx-ingress.md would make this issue progress better.
