### ISSUE TITLE
Release Notes appear to have wrong PR # for webhook issue

### ISSUE THREAD

**Issue by sdwire** [cert-manager/website#627]
https://cert-manager.io/docs/release-notes/release-notes-1.4/#helm-chart-webhook-externally-accessible-for-bare-metal references PR #4064 as the PR that adds the configuration to add a LoadBalancer IP address for the webhook service, but it appears that should reference PR #3876 instead.

**Comment by irbekrm** [comment]
Thank you for spotting the issue @sdwire !
