### ISSUE TITLE
PodSecurityPolicy: unable to admit  pod: []

### ISSUE THREAD

**Issue by jaylcm** [cert-manager/website#635]
Hi , the challenge pod unable to be created because of the PSP policy is enable, anyone can help? 

the error as below

Status:
  Presented:   false
  Processing:  true
  Reason:      pods "cm-acme-http-solver-" is forbidden: PodSecurityPolicy: unable to admit pod: []
  State:       pending

Error presenting challenge: pods "cm-acme-http-solver-" is forbidden: PodSecurityPolicy: unable to admit pod: []

**Comment by irbekrm** [comment]
Hi, 
I think it would make sense for you to create this issue against the [main cert-manager repo](https://github.com/jetstack/cert-manager) and add some extra information about your installation and what Pod Security Policy you have created.
