### ISSUE TITLE
Docs repeated in same page

### ISSUE THREAD

**Issue by criscola** [cert-manager/website#637]
Hello everyone, it appears the docs is being duplicated here: https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
`Secret` and `Issuer` resources are listed twice with no clear reason.

**Comment by irbekrm** [comment]
Hi @criscola ,

I think this is once for a configuration with [API token](https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens), once for [API keys](https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-keys) .

**Comment by criscola** [comment]
Ah yes, I did not notice that :P I think we can close this.
