### ISSUE TITLE
Securing NGINX-ingress: Silent failure after Step 7

### ISSUE THREAD

**Issue by blaise-sumo** [cert-manager/website#65]
The instructions are great, but they only consider the happy path, so for example, when I get to:
https://cert-manager.io/docs/tutorials/acme/ingress/#step-7-deploy-a-tls-ingress-resource and  get no response to:
`kubectl get certificate`
I don't know where to look for the problem. Since everything up to that point has gone smoothly, I have to assume that I did something wrong in the previous step.... but that's not the case.

---
1) The docs are much improved, because the steps are very clearly described, along with the expected output, thank you.

2) you should have stayed on readthedocs, Sphinx is much better for authoring complex docs than static site generators like Hugo because is easier to embed cross references to other parts of the doc.

**Comment by meyskens** [comment]
I think https://cert-manager.io/docs/faq/troubleshooting/ will solve the gap :) 

/close
