### ISSUE TITLE
Update Securing NGINX-ingress tutorial for apiVersion networking.k8s.io/v1

### ISSUE THREAD

**Issue by kcalmond** [cert-manager/website#709]
It looks like you need to modify some parts of this tutorial so that it works correctly with the latest version of ingress-nginx:  [Securing NGINX-ingress](https://cert-manager.io/docs/tutorials/acme/ingress/)

Specifically, to be consistent with this guidance "_from version 1.0.0 of the Ingress-NGINX Controller, a ingressclass object is required_" from [here](https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now).

**Comment by SgtCoDFish** [comment]
I believe the tutorial now works with the latest version! Thanks!
