### ISSUE TITLE
Issuer - Clarification needed

### ISSUE THREAD

**Issue by AlverezYari** [cert-manager/website#752]
> Issuers, and ClusterIssuers, are Kubernetes resources that represent certificate authorities (CAs) that are able to generate signed certificates by honoring certificate signing requests. All cert-manager certificates require a referenced issuer that is in a ready condition to attempt to honor the request.

Then there are zero bits explaining the differences between the two. What are the differences here? I can make and easy guess but with this stuff I feel like your whole doc section need to be tightened up a good bit. Maybe I'll make a PR when I stop wasting massive buckets of hours chasing ghost from poor documentation.

**Comment by JoshVanL** [comment]
https://cert-manager.io/docs/concepts/issuer/#namespaces

/close
