### ISSUE TITLE
Helm template fails with `--create-namespace`

### ISSUE THREAD

**Issue by esemeniuc** [cert-manager/website#770]
I'm trying to set up cert-manager to use a template. It fails when running this command:

```yaml
helm template cert-manager jetstack/cert-manager \
--namespace cert-manager \
--create-namespace \
--version v1.6.1 \
--set installCRDs=true > templates/cert-manager.custom.yaml
```
and running a subsequent the install, I see this:
```
➜  mydir git:(master) ✗ helm install MYPROJECT .
Error: INSTALLATION FAILED: namespaces "cert-manager" not found
```

System:
helm 3.7.1
kubectl 1.22.4
minikube 1.24

**Comment by irbekrm** [comment]
> and running a subsequent the install
 
Did you pass the `--create-namespace` flag to the install command? I don't think that `helm template` command creates actual cluster resources such as namespaces.

**Comment by irbekrm** [comment]
Closing as this is likely a user error.
