### ISSUE TITLE
Edit this page links are wrong for https://cert-manager.io/v*-docs/*

### ISSUE THREAD

**Issue by jsoref** [cert-manager/website#788]
## Actual
> https://github.com/cert-manager/website/edit/master/content/en/v1.6-docs/installation/helm.md

## Expected
> https://github.com/cert-manager/website/edit/release-1.6/content/en/docs/installation/helm.md

where `(content/en/)v([^-]*)-docs` maps to `release-$2/$1/docs`

**Comment by SgtCoDFish** [comment]
Thanks for the heads up on this @jsoref - good spot!

That said, I'm gonna close this without a fix, since the whole version-on-a-branch thing will ideally be going away (:pray:) and I'm not sure if we'll maintain the "edit this page" link after the website refresh in any case.
