### ISSUE TITLE
Uninstall link is broken

### ISSUE THREAD

**Issue by cemsbr** [cert-manager/website#84]
In https://cert-manager.io/docs/release-notes/release-notes-0.11/, there's a link to [uninstall cert-manager](https://docs.cert-manager.io/en/release-0.12/tasks/uninstall/), but it's broken.

**Comment by munnerz** [comment]
Fixed in https://github.com/jetstack/cert-manager/commit/7fa0a0394e8beedbe53f1f008c3680f05e9bb5f6 - thanks for the report! 😄
