### ISSUE TITLE
Add search functionality to the website

### ISSUE THREAD

**Issue by munnerz** [cert-manager/website#85]
To make it easy to discover information across the website, we should add search functionality that covers at least the documentation.

Hugo is a static site generator, so this normally involves utilising some additional tooling. [kubernetes.io](https://kubernetes.io/) uses "Google Custom Search", [Algolia](https://algolia.com) has also been recommended as a powerful alternative.

/help

**Comment by meyskens** [comment]
I contacted Algolia to see if they can get us the open source plan (with extra queries)
Looking into Hugo's docs there are several self hosted solutions but I guess that will have extra work.
I would prefer Algolia over Google as we can control our indexes with Algolia and can quickly change content and links.

**Comment by meyskens** [comment]
![Screenshot from 2020-02-20 13-52-32](https://user-images.githubusercontent.com/1625272/74935285-e56a9000-53df-11ea-94a7-d78d1d18f144.png)
I think this can be closed now we have search!
