### ISSUE TITLE
Update uninstall documentation

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/website#860]
At the moment our uninstall docs suggest that to uninstall cert-manager all cert-manager resources need to be deleted https://cert-manager.io/docs/installation/kubectl/#uninstalling. In reality this may not be desirable in cases where folks aim to keep the CRDs in th cluster and want to uninstall and reinstall, and would rather not lose their resources.

We should:
- update the docs to explain in which cases the resources need to be deleted before uninstalling (how to avoid getting into the problem with finalizers, see i.e [cert-manager#3851](https://github.com/cert-manager/cert-manager/issues/3851)
- Also add some note about what can potentially happen with `Secret`s _if_ the `Certificate`s have been deleted, see the discussion on https://github.com/cert-manager/cert-manager/issues/4788

**Comment by enjeck** [comment]
Seems related to issue #559 . I hope it's okay if I handle both in one PR
