### ISSUE TITLE
Google CloudDNS

### ISSUE THREAD

**Issue by lukeschlather** [cert-manager/website#91]
On https://cert-manager.io/docs/configuration/acme/dns01/google/ it says:

> Note: If you have already added the Secret but get an error: ...due to error processing: error getting clouddns service account: secret "XXX" not found, the Secret may be in the wrong namespace. If you’re configuring a ClusterIssuer, move the Secret to the Cluster Resource Namespace which is cert-manager by default. If you’re configuring an Issuer, the Secret should be stored in the same namespace as the Issuer resource.

It seems to me that the secrets always need to be in the kube-system namespace (which honestly seems like a very strange choice of namespace.) This is when I am attempting to create a ClusterIssuer in the cert-manager namespace. I'm not sure if there's a way to configure the Cluster Resource Namespace?

**Comment by meyskens** [comment]
cert-manager with ClusterIssuers will always use the secret from the namespace cert-manager is installed in, by default this is cert-manager

/triage support
