### ISSUE TITLE
GSoD2022: Improve the Navigation and Structure of the cert-manager Website by Mehak

### ISSUE THREAD

**Issue by mehak151** [cert-manager/website#921]
Hello team,

I'm a technical writer and I'm interested in the Improve the Navigation and Structure of the cert-manager Website project by [cert-manager.io](http://cert-manager.io/) in GSoD 2022.

I understand that the current state of the document is not user-focused and the whole structure needs to be revised to ensure the best user experience. I have worked on several product guides in the past, and I have a good understanding of hot technologies and frameworks such as Kubernetes. Event wrote a blog on it.

I'm excited to work on this, so together we can refine content and curate a better user experience as the users get more familiar with the product through the documentation. I have also emailed a detailed proposal with the subject **GSoD2022: Improve the Navigation and Structure of the cert-manager Website by Mehak** to the cert-manager.io team.

More about me:
I'm a technical writer and someone who believes in the power of content to make a difference. I believe that your product is only as good as the user who uses it. Therefore, it is of utmost importance to educate the end users so they can use the product to its full capacity and make the most out of it. I'm very process-oriented and I like to keep things organized. When I'm not writing, I'm generally painting on a digital canvas with my 2 years old. Long story short, I'm a mom who loves to code.

[LinkedIn](https://www.linkedin.com/in/mehak-saeed-29121a12a/)
[GitHub](https://github.com/mehak151/)

Published Work Samples

- [Project 1: Unfurl Documentation](https://docs.unfurl.run/)
- [Project 2: TopBraid EDG Documentation ](https://www.topquadrant.com/doc/7.2/)
- [Kubernetes introductory blog](https://drive.google.com/file/d/148s_j6PasS9P9U-FPFsMIJOBRs614RWI/view?usp=sharing)
- [Knowledge Base Articles](https://support.rush.app/)
- [Website content](https://xgrid.co/)
- [Customer Case Study](https://drive.google.com/file/d/1frNB1Ie4Zpre_-gu8-zkYNdD5QP5LjH7/view?usp=sharing)
- [Tech Writing Services](https://www.xninetysix.com/casestudy-fibermountain/#fibermountainTechnicalWriting)
- [API Document Sample (Swagger & Postman versions are also available)](https://drive.google.com/file/d/1v4j1nD0ROtHalz5ssJjQ35i2NgP-zmSC/view?usp=sharing)

More samples can be provided upon request.

Looking forward to hearing back from you.

Thanks

**Comment by wallrj** [comment]
Thank you for your interest. We are processing the applicants and we'll contact you if you are shortlisted for an interview.

**Comment by maelvls** [comment]
Closing now since the GSoD 2022 has ended.
