### ISSUE TITLE
GSoD2022: Dashamir Hoxha

### ISSUE THREAD

**Issue by dashohoxha** [cert-manager/website#922]
Some of my previous works related to documentation: https://gitlab.com/-/snippets/1861138
I don't have much experience with Kubernetes, but I can spend some time to get familiar with it, if needed.
If you wish to know more details about me or my experience, I would be happy to answer.

**Comment by wallrj** [comment]
Thank you for your interest. We are processing the applicants and we'll contact you if you are shortlisted for an interview.

**Comment by maelvls** [comment]
Closing now since the GSoD 2022 has ended.
