### ISSUE TITLE
GSoD2022: Improve the navigation and structure of the cert-manager website

### ISSUE THREAD

**Issue by enjeck** [cert-manager/website#923]
Hi everyone!

My name is Enjeck. I'd love to take on the project "_Improve the navigation and structure of the cert-manager website_" for Google Season of Docs 2022. Below, I shall highlight my skills and past experiences and how they relate to this role. 

### User research experience
- Last year, I spent 6 months working as a user research intern with the Kubernetes SIG Usability team. I participated in interviews with Kubernetes users, took down notes, cleaned up interview transcripts and highlighted relevant insights. The goal of this work was to put together a Jobs‑to‑be‑done study and help drive understanding of how users are using Kubernetes and how to improve their experience. I won a [2021 Kubernetes award for my contributions](https://www.kubernetes.dev/community/awards/2021/#usability). 
- I worked with MISP Project on user research and documentation tasks. I was responsible for finding out what sort of people use the project's software and what they're trying to accomplish, so that better documentation can be written to help users reach their goals. After weeks of research (going through GitHub issues, messages on community channels, chatting with a few community members), I wrote [user personas](https://github.com/enjeck/misp-book/blob/fca4a3570656592ff23f318c17e0d243ccd2e0b7/user-personas/README.md) and [user stories and workflows](https://github.com/enjeck/misp-book/blob/69ca4f4edaa03c549d98ea3aa54ff377ae2c0de7/user-stories/README.md). 

Drawing from my user research experiences, I can help cert-manager identify their target audience and identify the key tasks of each of these audiences.

### Technical writing experience
I have over 2 years of technical writing and documentation experience. Some sample writing:
- [Qubes OS troubleshooting docs](https://github.com/QubesOS/qubes-doc/pulls?q=is%3Apr+author%3Aenjeck+troubleshooting)
- Several technical articles on [my blog](https://enjeck.com/blog)
- [Umbrella user guide](https://secfirst.org/umbrella-manual/)
- [Tor Mobile user guide](https://github.com/enjeck/manual/blob/350a0c64564c016efe970dfd5efcd987626b010b/content/mobile-tor/contents.lr)
- [MISP Project contributing guide](https://github.com/enjeck/misp-book/blob/666d2a83b0a053192500cac050395f5c71591ac3/CONTRIBUTING.md)
- [Briar Project contributing guide](https://code.briarproject.org/briar/website/-/blob/015b634d79626b7f4bc9381d4a860b490aae0603/content/page/get-involved.md)

For most of the projects above, I also audited and restructured existing documentation, in addition to writing new docs. 
I, therefore, have the skills required to audit cert-manager's documentation, restructure the website and write contributor documentation.

### Web dev experience
Since this project involves cert-manager's website, I feel that I should mention that I'm very familiar with building websites. cert-manager's website uses Next.js, which I'm not very familiar with, but I've worked with similar frameworks and can easily learn it. I worked as a front end developer in the past, and have built several web projects:
- [My personal website with a MDX blog](https://github.com/enjeck/enjeck.github.io), built with Gatsby.js
- A [Google Search themed portfolio website](https://github.com/enjeck/gfolio), built with React.js

### cert-manager experience
I am still new to cert-manager. I have spent the past few days reading on the project and trying to understand the technical details. In addition, I have been working on a few website-related issues (#860, #559, #604) in order to get more familiar with cert-manager and the documentation workflow. During the next few weeks, I intend to learn more about cert-manager and make more contributions.

**Comment by maelvls** [comment]
Closing since the GSoD 2022 project has ended.
