### ISSUE TITLE
GSoD2022: Improve the Navigation and Structure of the cert-manager Website

### ISSUE THREAD

**Issue by mhmohona** [cert-manager/website#946]
Hello, I am Mahfuza and I am interested in _[Improve the Navigation and Structure of the cert-manager Website](https://github.com/cert-manager/website/blob/master/content/docs/contributing/google-season-of-docs/2022/improve-navigation-and-structure/README.md)_ project. 

As far as I understand, [Cert-manager.io](https://cert-manager.io/docs/) needs to be improved in the structure and navigation of doc, for which one should have experience in content writing as well as UX for a better outcome. 

I have experience in [blog writing](https://medium.com/@mhmohona), Git version control, NodeJS, k8s, GoLang, Linux OS. 

Please let me know if there is any other information I should provide. 
Thank you,
Mahfuza. 

cc: @wallrj @maelvls

**Comment by wallrj** [comment]
Thank you for your interest. We are processing the applicants and we'll contact you if you are shortlisted for an interview.
