### ISSUE TITLE
Docs: Example files not available

### ISSUE THREAD

**Issue by alexfornuto** [cert-manager/website#958]
The Yaml example files referenced in https://cert-manager.io/docs/tutorials/acme/pomerium-ingress/, which live in https://github.com/cert-manager/website/tree/master/content/docs/tutorials/acme/example, are not available on the live site:

```bash
kubectl create --edit -f https://cert-manager.io/docs/tutorials/acme/example/pomerium-staging-issuer.yaml
error: unable to read URL "https://cert-manager.io/docs/tutorials/acme/example/pomerium-staging-issuer.yaml", server reported 404 Not Found, status code=404
```

**Comment by maelvls** [comment]
Hi! A month ago, we migrated from Hugo to Next.js, which broke the way we were serving certain static files (ie files that aren’t markdown ending with mdx).

If we want to keep the old URL:

https://cert-manager.io/docs/tutorials/acme/example/pomerium-production-issuer.yaml

We probably need to find out how to serve static files directly along with the markdown files, which was easy with Hugo but became not possible with NextJS. 

Should we just move the file to the static/ path instead? @SgtCoDFish
