### ISSUE TITLE
Investigate styled 404 page

### ISSUE THREAD

**Issue by SgtCoDFish** [cert-manager/website#974]
Suggested by @wallrj

We used to have a broken but styled 404 page for the site. Now we have a default netlify page. We should get a working 404 styled page!

**Comment by prafull904434** [comment]
sir,may i work with this issue can you assign to me

**Comment by SgtCoDFish** [comment]
Sorry @prafull904434 it looks like this ticket was actually addresed by #1153 ! I don't think there's anything to do here so I'll close this. Thanks!
